"""Data models for the event analysis system."""

from __future__ import annotations

from datetime import datetime
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, model_validator


class AnalysisRequest(BaseModel):
    """User's analysis request."""

    event_description: str
    request_type: str = "full_analysis"
    requested_by: str = ""
    chat_id: int = 0


class ContextAnalysis(BaseModel):
    """ACT I: Context / situation board analysis."""

    event_name: str = ""
    event_name_en: str = ""
    date: str = ""
    category: str = ""
    summary: str = ""
    timeline: list[dict] = Field(default_factory=list)
    key_figures: list[dict] = Field(default_factory=list)
    background: str = ""
    sources: list[str] = Field(default_factory=list)
    glossary: list[dict] = Field(default_factory=list)
    confidence_score: float = 0.0


class PlayerAnalysis(BaseModel):
    """ACT II: Player identification and strategy analysis."""

    players: list[dict] = Field(default_factory=list)
    alliances: list[dict] = Field(default_factory=list)
    power_dynamics: str = ""
    summary: str = ""
    glossary: list[dict] = Field(default_factory=list)
    confidence_score: float = 0.0


class DynamicsAnalysis(BaseModel):
    """ACT III: Structural dynamics and game theory analysis."""

    framework: str = ""
    core_tension: str = ""
    asymmetries: list[dict] = Field(default_factory=list)
    feedback_loops: list[dict] = Field(default_factory=list)
    why_unresolved: str = ""
    tipping_points: list[dict] = Field(default_factory=list)
    counter_view: str = ""
    cognitive_biases: list[str] = Field(default_factory=list)
    key_insight: str = ""
    summary: str = ""
    glossary: list[dict] = Field(default_factory=list)
    confidence_score: float = 0.0


class ChainReactionAnalysis(BaseModel):
    """ACT IV: Cause-effect chain and domino effect analysis."""

    chain: list[dict] = Field(default_factory=list)
    feedback_loops: list[dict] = Field(default_factory=list)
    break_points: list[dict] = Field(default_factory=list)
    wildcards: list[dict] = Field(default_factory=list)
    worst_case: str = ""
    summary: str = ""
    glossary: list[dict] = Field(default_factory=list)
    confidence_score: float = 0.0


class ScenarioAnalysis(BaseModel):
    """ACT V+VI: Scenario design and watch signal identification."""

    scenarios: list[dict] = Field(default_factory=list)
    watch_signals: list[dict] = Field(default_factory=list)
    invalidation_conditions: list[str] = Field(default_factory=list)
    base_case_summary: str = ""
    summary: str = ""
    glossary: list[dict] = Field(default_factory=list)
    confidence_score: float = 0.0


class VisualAnalysis(BaseModel):
    """Visual elements generated by the Visual Analyst."""

    hero_visual_type: str = ""
    hero_title: str = ""
    svg_content: str = ""
    mermaid_code: str = ""
    leaflet_config: dict = Field(default_factory=dict)
    chart_config: dict = Field(default_factory=dict)
    key_metrics: list[dict] = Field(default_factory=list)
    glossary: list[dict] = Field(default_factory=list)
    confidence_score: float = 0.0


class NarrativeSection(BaseModel):
    """A single section in the dynamic report narrative."""

    section_id: str = ""
    act_label: str = ""
    title: str = ""
    data_source: str = ""
    narrative_bridge: str = ""
    subsections: list[str] = Field(default_factory=list)


class NarrativePlan(BaseModel):
    """Claude-generated plan for report section ordering."""

    report_theme: str = ""
    sections: list[NarrativeSection] = Field(default_factory=list)


# ====== V3 Strategy Models (Step 1 — REFACTOR_V3_PLAN.md §4.1) ======

UserIntent = Literal[
    "what_happened",       # 사실 파악
    "why_happened",        # 원인 분석
    "who_benefits",        # 이해관계 분석
    "where_spreads",       # 파급효과
    "what_next",           # 시나리오/전망
    "where_vulnerable",    # 취약점 분석
    "what_to_do",          # 의사결정
]


class EvidenceNeed(BaseModel):
    """수집해야 할 증거 명세 (Strategy Planner 산출)."""

    need_id: str
    description: str
    expected_source_types: list[str] = Field(default_factory=list)
    priority: Literal["P0", "P1", "P2"] = "P1"


class ReportSectionPlan(BaseModel):
    """보고서 섹션 계획. Step 3 블록 시스템 도입 후 본격 사용."""

    section_id: str
    title: str
    purpose: str = ""
    block_types: list[str] = Field(default_factory=list)


class VisualizationSpec(BaseModel):
    """시각화 사양. Visual Analyst 가 참조할 명세."""

    visual_id: str
    visual_type: Literal[
        "svg_relationship", "leaflet_map", "canvas_chart",
        "mermaid_flow", "d3_custom",
    ]
    purpose: str = ""
    data_source: str = ""


class AnalysisStrategy(BaseModel):
    """분석 전체 설계도 — dict 기반 strategy 의 정식 Pydantic 승격본.

    Step 1 (v2.5.0): 정식 모델로 도입. core_questions, user_intent, recommended_lenses 신설.
    Step 5 (V3 후): legacy_directives 제거, lens-driven directives 로 대체 예정.

    SSOT: 본 정의. ``docs/DATA_MODELS.md`` 는 도식 미러.
    """

    model_config = ConfigDict(populate_by_name=True)

    # === Intent + 질문 (Step 1 신규) ===
    event_type: str
    user_intent: UserIntent
    intent_confidence: float = Field(ge=0.0, le=1.0)
    multi_intent_secondary: list[UserIntent] = Field(default_factory=list)

    core_questions: list[str] = Field(min_length=1, max_length=7)
    recommended_lenses: list[str] = Field(min_length=1, max_length=4)

    # === 계획 (Step 1 신규, Step 2~3 본격 활용) ===
    evidence_plan: list[EvidenceNeed] = Field(default_factory=list)
    report_archetype: str = "six_act_theater"
    section_plan: list[ReportSectionPlan] = Field(default_factory=list)
    visualization_plan: list[VisualizationSpec] = Field(default_factory=list)

    # === 실행 옵션 (alias='skip' 으로 v2 dict 호환 유지) ===
    skip_agents: list[str] = Field(default_factory=list, alias="skip")
    uncertainty_policy: Literal["aggressive", "moderate", "conservative"] = "moderate"
    theme: str = "burgundy"

    # === Step 1 한정 transitional shim ===
    # v2 의 dict 기반 per-agent directive 문자열을 보존하기 위한 임시 필드.
    # Step 5 lens pool 도입 시 제거됨. 신규 코드는 recommended_lenses 를 사용할 것.
    legacy_directives: dict[str, str] = Field(default_factory=dict)

    @model_validator(mode="after")
    def validate_lens_question_alignment(self) -> "AnalysisStrategy":
        if len(self.core_questions) > 0 and len(self.recommended_lenses) == 0:
            raise ValueError(
                "Core questions exist but no lenses recommended. "
                "Strategy must propose at least one lens for any core question."
            )
        return self


# ====== V3 Block Rendering (Step 3 — v2.7.0) ======

BlockType = Literal[
    "narrative",            # 산문 단락
    "claim_card",           # 주장 + 근거 카드 (Step 4 에서 본격 활용)
    "evidence_table",       # 증거 표 (Step 4)
    "timeline",             # 시계열
    "matrix",               # 비교 매트릭스
    "actor_cards",          # 행위자 카드 (legacy player_card 대체)
    "flow_chain",           # 인과 사슬 (legacy chain_reaction 대체)
    "scenario_table",       # 시나리오 표
    "decomposition",        # 메커니즘 분해
    "argument_pair",        # ACH 가설 대결
    "data_series",          # 수치 시계열
    "watchlist",            # 감시 신호 그리드
    "qna",                  # 흔한 질문 응답 (Step 4+)
    "callout",              # 강조 인용
    "counter_hypothesis",   # 반대 가설 박스
    "decision_matrix",      # 의사결정 매트릭스
    "risk_matrix",          # 리스크 매트릭스
]


class AnalysisBlock(BaseModel):
    """보고서 렌더링의 기본 단위 — V3 매크로 1:1 강결합 해소.

    템플릿은 ``block.payload`` 만 참조해야 한다 (Anti-pattern #8). payload 스키마는
    block_type 별로 자유 dict — 본 정의는 컨테이너만 책임지고, 스키마는
    `docs/CATALOGS.md §4` 가 사람-친화 가이드를 제공한다.
    """

    block_id: str
    block_type: BlockType
    title: str = ""
    purpose: str = ""
    payload: dict = Field(default_factory=dict)
    related_findings: list[str] = Field(default_factory=list)
    section_id: str = ""


# ====== V3 Claim / Evidence / Confidence (Step 4 — v2.8.0, REFACTOR_V3_PLAN.md §4.1) ======

ClaimType = Literal["fact", "inference", "prediction", "judgment"]
Reliability = Literal["primary", "secondary", "expert", "model_inference"]


class Evidence(BaseModel):
    """추적 가능한 증거 단위.

    SSOT: 본 정의. ``claim_card`` / ``evidence_table`` 블록의 payload 와 lens runner 산출에
    공통으로 쓰인다.
    """

    evidence_id: str  # 예: "E-001"
    source_url: str = ""
    quote_or_data: str = ""
    reliability: Reliability = "model_inference"
    timestamp: str = ""
    supports_claims: list[str] = Field(default_factory=list)


class Claim(BaseModel):
    """주장 단위. 반드시 evidence_id 를 1개 이상 가짐.

    Anti-pattern #4 방지: ``evidence_ids`` 가 비어 있으면 ValidationError.
    """

    claim_id: str  # 예: "C-001"
    statement: str
    claim_type: ClaimType = "inference"
    evidence_ids: list[str] = Field(min_length=1)

    @model_validator(mode="after")
    def must_have_evidence(self) -> "Claim":
        if len(self.evidence_ids) == 0:
            raise ValueError(
                f"Claim {self.claim_id} requires at least one evidence_id. "
                f"This is a hard constraint (Anti-pattern #4)."
            )
        return self


class ConfidenceProfile(BaseModel):
    """단일 confidence_score 대체. 3축 분해. Anti-pattern #10 회피.

    가중평균 ``aggregate`` 는 단일 점수가 필요한 좁은 곳에서만 사용 — 신규 코드는 3축을
    따로따로 노출하는 게 원칙.
    """

    source_diversity: float = Field(ge=0.0, le=1.0, default=0.5)
    data_freshness: float = Field(ge=0.0, le=1.0, default=0.5)
    expert_consensus: float = Field(ge=0.0, le=1.0, default=0.5)

    @property
    def aggregate(self) -> float:
        return (
            0.4 * self.source_diversity
            + 0.3 * self.data_freshness
            + 0.3 * self.expert_consensus
        )


class AnalyticalFinding(BaseModel):
    """렌즈가 산출하는 단위 결과 (Step 5 lens runner 도입 전엔 v2 분석 래퍼)."""

    finding_id: str
    lens_id: str
    answers_question: str = ""
    main_claim: Claim
    supporting_findings: list[str] = Field(default_factory=list)
    evidence: list[Evidence] = Field(default_factory=list)
    confidence: ConfidenceProfile

    counter_hypothesis: str = ""
    counter_required_evidence: list[str] = Field(default_factory=list)


class JudgmentVerdict(BaseModel):
    """Synthesis Judge 의 종합 판단. Anti-pattern #5 (모순 봉합) 회피 — contradictions 필드는
    명시적으로 모순을 *드러낸다*.
    """

    main_judgment: str = ""
    base_scenario: str = ""
    biggest_uncertainty: str = ""
    contradictions: list[dict] = Field(default_factory=list)  # [{lens_a, lens_b, conflict, resolution}]
    counter_hypothesis: str = ""
    counter_evidence_needed: list[str] = Field(default_factory=list)
    confidence: ConfidenceProfile = Field(default_factory=ConfidenceProfile)


class FullAnalysisResult(BaseModel):
    """Complete analysis result from all agents."""

    request: AnalysisRequest
    strategy: AnalysisStrategy | None = None  # V3 Step 1
    blocks: list[AnalysisBlock] = Field(default_factory=list)  # V3 Step 3
    findings: list[AnalyticalFinding] = Field(default_factory=list)  # V3 Step 4
    judgment: JudgmentVerdict | None = None  # V3 Step 4
    context: ContextAnalysis | None = None
    players: PlayerAnalysis | None = None
    dynamics: DynamicsAnalysis | None = None
    chain_reaction: ChainReactionAnalysis | None = None
    scenarios: ScenarioAnalysis | None = None
    visuals: VisualAnalysis | None = None
    executive_summary: str = ""
    report_url: str = ""
    report_path: str = ""
    analysis_timestamp: str = Field(
        default_factory=lambda: datetime.now().isoformat()
    )
    total_duration_seconds: float = 0.0
    # NOTE (V3 Step 4 / Anti-pattern #10): ``ContextAnalysis.confidence_score`` 등 기존
    # ``confidence_score: float`` 필드들은 v2 호환 목적으로 보존되며 deprecated 상태.
    # 신규 코드는 ``ConfidenceProfile`` (3축) 을 사용. v3.0.0 릴리스 시점에 일괄 정리 예정.

